#!/bin/bash

# Quick script to show exact restrictions to add

echo "🔒 Google API Key Website Restrictions"
echo ""
echo "Copy these restrictions to Google Cloud Console:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "HTTP Referrers (Web Sites):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "https://www.spect-it.com/*"
echo "https://spect-it.com/*"
echo "https://spect-it.vercel.app/*"
echo "https://*.vercel.app/*"
echo "http://localhost:3000/*"
echo "http://127.0.0.1:3000/*"
echo "http://localhost/*"
echo "http://127.0.0.1/*"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "API Restrictions (Enable Only):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Places API"
echo "✅ Maps JavaScript API"
echo "✅ Geocoding API"
echo "✅ Distance Matrix API (if used)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Go to: https://console.cloud.google.com/apis/credentials"
echo "Edit your API key → Add restrictions above → Save"
echo ""

