#!/bin/bash

# Fix Current Setup - Complete Guide
# Fixes all configuration issues without rebuilding

set -e

cd "$(dirname "$0")"

echo ""
echo "╔══════════════════════════════════════════════════════════════════════════╗"
echo "║     🔧 FIXING CURRENT SETUP - STEP BY STEP                              ║"
echo "╚══════════════════════════════════════════════════════════════════════════╝"
echo ""

echo "✅ Opening all necessary pages..."
echo ""

# Open pages
open "https://github.com/TanyaStrauss1/Spect-IT/settings/pages"
open "https://appstoreconnect.apple.com/teams/c5c5f5d2-8ebe-443d-957f-b4038c7db237/apps/6755681856/appstore"
open "https://appstoreconnect.apple.com/teams/c5c5f5d2-8ebe-443d-957f-b4038c7db237/apps/6755681856/testflight"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 FIX 1: ENABLE GITHUB PAGES (2 minutes)"
echo ""
echo "   In GitHub Settings (just opened):"
echo "   1. Under 'Source' section"
echo "   2. Select 'GitHub Actions'"
echo "   3. Click 'Save'"
echo "   4. Wait 1-2 minutes for deployment"
echo ""
echo "   ✅ Your site will be at:"
echo "      https://tanyastrauss1.github.io/Spect-IT/privacy-policy.html"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 FIX 2: SELECT BUILD IN APP STORE CONNECT (2 minutes)"
echo ""
echo "   In App Store Connect (just opened):"
echo "   1. Go to 'App Store' tab"
echo "   2. Scroll to 'Build' section"
echo "   3. Click '+' or 'Select a build'"
echo "   4. Select Version 1.0, Build 1"
echo "   5. Build should show 'Ready to Submit' or 'Ready to Test'"
echo ""
echo "   ⚠️  If build not available:"
echo "      → Check TestFlight tab (also opened)"
echo "      → Wait if status is 'Processing'"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 FIX 3: COMPLETE APP STORE SUBMISSION (20 minutes)"
echo ""
echo "   In App Store Connect → App Store tab:"
echo ""
echo "   1. App Information:"
echo "      → Name: Spect-IT"
echo "      → Category: Medical or Health & Fitness"
echo "      → Age Rating: Complete questionnaire"
echo "      → Description: Write app description"
echo "      → Keywords: eye test, vision test, eye health"
echo "      → Privacy Policy: https://tanyastrauss1.github.io/Spect-IT/privacy-policy.html"
echo "      → Support URL: https://tanyastrauss1.github.io/Spect-IT/"
echo ""
echo "   2. Screenshots:"
echo "      → Upload at least 1 set (iPhone 6.7\": 1290 x 2796 pixels)"
echo ""
echo "   3. Version Information:"
echo "      → Version: 1.0"
echo "      → What's New: Initial release notes"
echo ""
echo "   4. App Review Information:"
echo "      → Contact: tanstrauss@gmail.com"
echo "      → Phone: (your phone number)"
echo ""
echo "   5. Submit:"
echo "      → Review all information"
echo "      → Click 'Submit for Review'"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ VERIFICATION CHECKLIST:"
echo ""
echo "   After completing fixes:"
echo ""
echo "   [ ] GitHub Pages enabled and accessible"
echo "   [ ] Build selected in App Store Connect"
echo "   [ ] All required fields completed"
echo "   [ ] Screenshots uploaded"
echo "   [ ] Submitted for review"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📖 DETAILED GUIDES:"
echo ""
echo "   • ENABLE_GITHUB_PAGES.md - GitHub Pages setup"
echo "   • SELECT_BUILD_FOR_REVIEW.md - Build selection"
echo "   • APP_STORE_SUBMISSION_CHECKLIST.md - Complete checklist"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⏱️  TOTAL TIME: ~30 minutes"
echo ""
echo "✅ All pages opened - follow the steps above!"
echo ""

