#!/bin/bash

# Setup Xcode Cloud with connected device registration

set -e

cd "$(dirname "$0")"

echo ""
echo "╔══════════════════════════════════════════════════════════════════════════╗"
echo "║     📱 SETTING UP XCODE CLOUD WITH CONNECTED DEVICE                     ║"
echo "╚══════════════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 CONFIGURATION SUMMARY:"
echo ""
echo "   Team ID: P7BPRR2MY3"
echo "   Bundle ID: com.spectit.app"
echo "   Scheme: SpectIT"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📱 STEP 1: REGISTER CONNECTED DEVICE IN XCODE"
echo ""
echo "   1. In Xcode: Window → Devices and Simulators"
echo "   2. Your connected iPhone/iPad should appear"
echo "   3. If it shows 'Not Registered':"
echo "      → Click 'Use for Development'"
echo "      → Sign in with your Apple ID if prompted"
echo "      → This adds device to your Developer account"
echo "   4. Device will now be available for provisioning profiles"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔧 STEP 2: CONFIGURE SIGNING IN XCODE"
echo ""
echo "   1. Click project (blue icon) → Select 'SpectIT' target"
echo "   2. Go to 'Signing & Capabilities' tab"
echo "   3. Select 'Release' configuration (top of tab)"
echo "   4. ✅ Check 'Automatically manage signing'"
echo "   5. Select Team: P7BPRR2MY3"
echo "   6. Xcode will create provisioning profile with your device"
echo "   7. Wait for green checkmark ✅"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "☁️  STEP 3: VERIFY XCODE CLOUD CONFIGURATION"
echo ""

# Check workflow file
if [ -f "ios/.xcodecloud/workflow.yml" ]; then
    echo "   ✅ Xcode Cloud workflow file exists"
    TEAM_ID=$(grep "team_id" ios/.xcodecloud/workflow.yml | cut -d: -f2 | tr -d ' ')
    echo "   → Team ID in workflow: $TEAM_ID"
else
    echo "   ⚠️  Workflow file missing"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 STEP 4: ENABLE XCODE CLOUD IN APP STORE CONNECT"
echo ""
echo "   1. Go to: https://appstoreconnect.apple.com"
echo "   2. My Apps → Spect-IT"
echo "   3. Xcode Cloud → Enable (if not already)"
echo "   4. Products → Connect Repository"
echo "   5. Select: TanyaStrauss1/Spect-IT"
echo "   6. Branch: main"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📦 STEP 5: CREATE WORKFLOW IN XCODE"
echo ""
echo "   1. In Xcode: Product → Xcode Cloud → Create Workflow"
echo "   2. Or: Xcode → Settings → Cloud → Create Workflow"
echo "   3. Configure:"
echo "      → Name: Build and Distribute Spect-IT"
echo "      → Repository: TanyaStrauss1/Spect-IT"
echo "      → Branch: main"
echo "      → Scheme: SpectIT"
echo "      → Configuration: Release"
echo "   4. Add Actions:"
echo "      → ✅ Archive"
echo "      → ✅ Distribute"
echo "   5. Save workflow"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ BENEFITS OF DEVICE REGISTRATION:"
echo ""
echo "   • Xcode can create development profiles (for testing)"
echo "   • Device available for ad-hoc distribution"
echo "   • Helps with provisioning profile creation"
echo "   • Xcode Cloud can use device for testing (optional)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 NOTE:"
echo ""
echo "   Xcode Cloud builds don't actually need a connected device."
echo "   But registering it helps with:"
echo "   • Provisioning profile creation"
echo "   • Local testing before cloud builds"
echo "   • Development builds"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 TO TEST XCODE CLOUD:"
echo ""
echo "   git add ."
echo "   git commit -m 'Configure Xcode Cloud with device'"
echo "   git push"
echo ""
echo "   → Xcode Cloud will automatically build on push!"
echo ""

