#!/bin/bash

echo "╔══════════════════════════════════════════════════════════════════════════╗"
echo "║          🚀 SUPABASE SETUP QUICK START                                    ║"
echo "╚══════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "This script will help you set up Supabase for Spect-IT"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: Create Supabase Account"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://supabase.com"
echo "2. Sign up or sign in"
echo "3. Click 'New Project'"
echo "4. Fill in:"
echo "   - Name: spect-it"
echo "   - Database Password: (choose a strong password)"
echo "   - Region: Choose closest to your users"
echo "5. Click 'Create new project'"
echo ""
read -p "Press Enter when you've created your Supabase project..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Get API Credentials"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. In Supabase dashboard, go to: Settings → API"
echo "2. Copy your Project URL"
echo "3. Copy your anon/public key"
echo ""
read -p "Enter your Supabase Project URL: " SUPABASE_URL
read -p "Enter your Supabase anon key: " SUPABASE_KEY

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: Update Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Update supabase-config.js
sed -i '' "s|url: 'https://your-project.supabase.co'|url: '$SUPABASE_URL'|g" supabase-config.js
sed -i '' "s|anonKey: 'your-anon-key-here'|anonKey: '$SUPABASE_KEY'|g" supabase-config.js

echo "✅ Configuration updated in supabase-config.js"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 4: Create Database Tables"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. In Supabase dashboard, go to: SQL Editor"
echo "2. Copy the SQL from: SUPABASE_SETUP.md"
echo "3. Paste and run it"
echo ""
echo "Or run this command to open the SQL file:"
echo "   cat SUPABASE_SETUP.md | grep -A 200 'CREATE TABLE'"
echo ""
read -p "Press Enter when you've created the database tables..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ SETUP COMPLETE!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Your Supabase integration is ready!"
echo ""
echo "Test it by:"
echo "1. Opening your website"
echo "2. Opening browser console (F12)"
echo "3. Running: window.SupabaseStorage.isAvailable()"
echo "4. Should return: true"
echo ""
echo "📄 Full setup guide: SUPABASE_SETUP.md"
echo ""

